### ISSUE TITLE
Total not displayed at the time of check out in PoS

### ISSUE THREAD

**Issue by Amangnair** [LalanaChami/Pharmacy-Mangment-System#204]
![Screenshot (683)](https://user-images.githubusercontent.com/47894206/163380350-24a28aaf-e54d-4e89-980f-6b6cf6403e30.png)

After adding the required drugs into the bill, on clicking the check out button, it's not displaying the total amount including the (qty*price) value in the right side Check Out box; rather it displays **NaN**

please help w/ this problem

**Comment by LalanaChami** [comment]
Please debug and check weather onAddToCheckout function in  BillItemComponent gets string values rather than number , if its the case parse the string values before calculating the string values.

**Comment by Amangnair** [comment]
Can u plse guide me in debugging or what changes should i make in below screenshot

![Screenshot (685)](https://user-images.githubusercontent.com/47894206/163671026-2174c42a-3e35-42c5-b979-9bf982978650.png)

**Comment by LalanaChami** [comment]
Please check below link details about debugging 
https://developer.chrome.com/docs/devtools/javascript/

**Comment by zakeerms** [comment]
Getting NaN for many variables mentioned in the for loop 

Like x,z etc please check 

![image](https://user-images.githubusercontent.com/16174872/163703500-3e14f0f4-59b2-4c44-8bd7-86a079ac6f30.jpeg)
