### ISSUE TITLE
Empty CSS files.

### ISSUE THREAD

**Issue by upchinchole** [LalanaChami/Pharmacy-Mangment-System#56]
Almost all the CSS files in the projects are empty, without any single line.
Also, their is some error in bill-item.component.ts file in <div class="slides-wrapper" line.
It will be very nice if you please upload CSS files again.

**Comment by LalanaChami** [comment]
Actually I have used Bulma CSS framework as my styling for the project. Only custom styled components have an un empty CSS file. But for sure I'll delete the empty CSS files in other components when releasing a build. Thank you for opening the issue

**Comment by upchinchole** [comment]
![Screenshot (153)](https://user-images.githubusercontent.com/27041188/82525315-ae2a8d00-9b4e-11ea-9217-42b04c3af74e.png)

So, can you help me in proceeding with the UI. I have attached a screenshot from my browser, UI is looking messed up. Can you guide, how should I work with Bulma CSS for this particular project, since you said, rest of the CSS files you'll be deleting.

**Comment by LalanaChami** [comment]
Hey, please make sure that all the dependencies are completely downloaded before hitting the       " ng serve ", If you are using a linux based OS , make sure to run "sudo npm install" to download all the dependencies needed. And if you are using a windows run the terminal as Admin and run "npm install". The interface should look like
![image](https://user-images.githubusercontent.com/33516757/82570166-de9a1780-9b9e-11ea-8b0c-4eb436893468.png)
The Cashier dashboard.
![Uploading image.png…]()
The Pharmacist dashboard.

Bulma is just a CSS framwork similar to Bootstrap. Make sure to run "npm install" before compiling.
